### ISSUE TITLE
Install/update attempts to clone to nested directory if specified path already exists

### ISSUE THREAD

**Issue by Erich-McMillan** [jacebrowning/gitman#228]
When using `gitman update` to clone a sub-project if the specified checkout path already exists as a folder then the sub-project cannot be cloned.

Given the following project structure:
```
Src\(some folders here)
Edk2\ (empty folder)
gitman.yml
```

With gitman.yml:
```
location: .
sources:
  - name: Edk2
    type: git
    repo: https://github.com/tianocore/edk2.git
    sparse_paths:
      -
    rev: EDK2_Trunk_Intel-hp
    link:
    scripts:
      -
groups:
  -
```

Then the following error occurs:

```
PS ${project_path}> gitman update

Updating dependencies...

$ cd /D ${project_path}

  $ cd /D Edk2
Traceback (most recent call last):
  File "${user_path}\.pyenv\pyenv-win\versions\3.8.1-amd64\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "${user_path}\.pyenv\pyenv-win\versions\3.8.1-amd64\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "${user_path}\.local\bin\gitman.exe\__main__.py", line 7, in <module>
  File "${user_path}\.local\pipx\venvs\gitman\lib\site-packages\gitman\cli.py", line 226, in main
    _run_command(function, args, kwargs)
  File "${user_path}\.local\pipx\venvs\gitman\lib\site-packages\gitman\cli.py", line 297, in _run_command
    success = function(*args, **kwargs)
  File "${user_path}\.local\pipx\venvs\gitman\lib\site-packages\gitman\commands.py", line 17, in wrapped
    result = func(*args, **kwargs)
  File "${user_path}\.local\pipx\venvs\gitman\lib\site-packages\gitman\commands.py", line 158, in update
    count = config.install_dependencies(
  File "${user_path}\.local\pipx\venvs\gitman\lib\site-packages\gitman\models\config.py", line 103, in install_dependencies
    source.update_files(
  File "${user_path}\.local\pipx\venvs\gitman\lib\site-packages\gitman\models\source.py", line 79, in update_files
    raise self._invalid_repository
gitman.exceptions.InvalidRepository:

            Not a valid repository: ${project_path}\Edk2\Edk2
            During install you can rebuild a repo with a missing .git directory using the --force option
```

Specifically that I expected Edk2 to be checked out to ${project_path}\Edk2, but it was instead checked out to ${project_path}\Edk2\Edk2 and then failed.

If the empty Edk2 folder is removed then the sub-project can be successfully checked out.

`git clone https://github.com/tianocore/edk2.git Edk2` successfully cloned the project into empty Edk2\ folder.

I'm cloning gitman code to see if I can fix the issue and create a pull request for review.

**Comment by Erich-McMillan** [comment]
@jacebrowning, I opened a [PR](https://github.com/jacebrowning/gitman/pull/229) that fixes the issue locally for me and does not appear to break existing update/install functionality.

True issue appears to be that there was a check in source.py to ensure the checkout destination did not exist prior to checkout, but an empty checkout destination is also valid in `git checkout` so I added a check for empty directory.

**Comment by jacebrowning** [comment]
This fix is available in this beta release: https://pypi.org/project/gitman/2.2b1/
