### ISSUE TITLE
UnicodeDecodeError occurs when running gitman update/install in Windows

### ISSUE THREAD

**Issue by sch0125** [jacebrowning/gitman#271]
When a commit contains Unicode right double quotation mark `”` (`U+201d`, hex: `0xe2 0x80 0x9d`) in commit message, the following error appears when running gitman update or gitman install in Windows:

```
z:\test_repo\TestDep>git log -1
commit 138bbda511fd181f38547fc16dd5d6e37bd30f51 (HEAD, test)
Author: Sc <sch0125@gmail.com>
Date:   Tue Feb 22 12:47:36 2022 +0800

    ”

z:\test_repo\TestDep>cd ..

z:\test_repo>poetry run gitman install TestDep

Installing dependencies...

$ cd /D z:\test_repo

  $ cd /D TestDep
  $ git checkout --force 138bbda511fd181f38547fc16dd5d6e37bd30f51
Traceback (most recent call last):
  File "C:\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "z:\test_repo\.venv\Scripts\gitman.exe\__main__.py", line 7, in <module>
  File "Z:\test_repo\.venv\lib\site-packages\gitman\cli.py", line 239, in main
    _run_command(function, args, kwargs)
  File "Z:\test_repo\.venv\lib\site-packages\gitman\cli.py", line 325, in _run_command
    success = function(*args, **kwargs)
  File "Z:\test_repo\.venv\lib\site-packages\gitman\commands.py", line 17, in wrapped
    result = func(*args, **kwargs)
  File "Z:\test_repo\.venv\lib\site-packages\gitman\commands.py", line 105, in install
    count = config.install_dependencies(
  File "Z:\test_repo\.venv\lib\site-packages\gitman\models\config.py", line 107, in install_dependencies
    source.update_files(
  File "Z:\test_repo\.venv\lib\site-packages\gitman\models\source.py", line 133, in update_files
    git.update(
  File "Z:\test_repo\.venv\lib\site-packages\gitman\git.py", line 215, in update
    git('checkout', '--force', rev, _stream=False)
  File "Z:\test_repo\.venv\lib\site-packages\gitman\git.py", line 16, in git
    return call('git', *args, **kwargs)
  File "Z:\test_repo\.venv\lib\site-packages\gitman\shell.py", line 45, in call
    output = command.stdout.readline()
  File "C:\Python39\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 27: character maps to <undefined>

```

cc: @brandonaut, @Erich-McMillan

**Comment by sch0125** [comment]
Try to have a PR #272 to fix this issue

**Comment by jacebrowning** [comment]
The fix for this is available here: https://pypi.org/project/gitman/3.1/
